# Generated by Django 2.2.12 on 2021-02-28 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='price',
            field=models.PositiveIntegerField(default=110, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='meal1',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='meal2',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='meal3',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='meal4',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='supper1',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='supper2',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='supper',
            name='price',
            field=models.PositiveIntegerField(default=25, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='', max_length=1000, null=True)),
                ('info', models.TextField(blank=True, max_length=2000)),
                ('desert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Desert')),
                ('meal1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal1', to='accounts.Meal')),
                ('meal2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal2', to='accounts.Meal')),
                ('meal3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal3', to='accounts.Meal')),
                ('meal4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal4', to='accounts.Meal')),
                ('supper1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supper1', to='accounts.Supper')),
                ('supper2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supper2', to='accounts.Supper')),
            ],
        ),
    ]
