# Generated by Django 3.1.7 on 2021-03-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210304_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='meal1_portions',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='meal2_portions',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='meal3_portions',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='meal4_portions',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='supper1_portions',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='supper2_portions',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
